### ISSUE TITLE
Just Querying Info

### ISSUE THREAD

**Issue by TestCandidate** [kixelated/steamcache#2]
Hi @kixelated 

Coming from steamcache/generic, 
I had issues updating game clients, such as Origin. and other reportedly having issues with other clients like battle net.

I am just wondering if your fork solve these issues? 
is there any problem updating? 

on another note, should I use steamcache-dns with your container? If so, what parameter should i use? the STEAMCACHE_IP or the LANCACHE_IP

Thanks.

**Comment by kixelated** [comment]
Hey TestCandidate, steamcache/generic is just busted in general and they don't want to fix it. You don't want to use steamcache-dns because my fork works a little differently and handles DNS anyway. Just start from scratch and follow the README.

**Comment by TestCandidate** [comment]
Thank you @kixelated

I'll give your fork a shot tonight. 
It's not supposed to have any issues with client updates? 

On the other, I'd like to ask: what happens when the drive is full?  Is the system smart as in getting rid of older stuff? Or how does that work? 

Thanks!

**Comment by kixelated** [comment]
Everything should just work. I'm using it for the gaming PCs here at Twitch.

There's a hard-coded 900GB limit, after which the last used files will be deleted to make space. One day I will figure out how to make it an environment variable but you can just edit the code to your hard drive size for now. This is a feature that upstream steamcache lacks.

**Comment by TestCandidate** [comment]
Thank you for the reply.

I See. well, I'm setting it up at a gaming network cafe. but I'm doing a couple of tests first.
I'll spin this off tonight and do a couple of tests.

I am using a 480GB SSD. i don't think i need more for the moment. 
but could you point out to me the file that contains the hard coded limit so i could modify? 

Thanks a bunch

**Comment by kixelated** [comment]
https://github.com/kixelated/steamcache-http/blob/master/overlay/etc/nginx/steamcache/global.conf#L12

Change the 900. Also keep in mind the repository currently uses submodules.

**Comment by TestCandidate** [comment]
awesome thank you.  I'll change that to 400.

What do you mean by keeping the use of submodules in mind?

**Comment by kixelated** [comment]
It'll make forking a little more complicated if you take that route, but otherwise doesn't stop you from just making local changes.

**Comment by TestCandidate** [comment]
No Problem. I edited the file manually for now. no need to fork ATM.
I did the setup - Tested steam. seems to be working perfectly.

Origin is currently updating without issues.
I'll test its caching soon.

Thank you for all the help and for your work. This is very useful for me 👍

**Comment by TestCandidate** [comment]
Okay so I'm testing origin and something definitely is wrong.
The speed is horrible.
![image](https://cloud.githubusercontent.com/assets/22873773/26651575/cd397626-4655-11e7-820c-114b60a94553.png)

I thought it could be their servers, so i switched the dns settings. everything is fine when routing normally.
but when i change back to the cache dns, the speed goes extremely slow. (and it hangs for few minutes on 0B/s)

Any ideas what might be causing that? steam works normally

**Comment by kixelated** [comment]
I haven't tested Origin lately so it's possible they changed something. Last time I checked, they were using range requests. We slice the download into 2MB chunks but I don't think that's the issue.

I'll try origin later tonight and see if I get the same issue. I usually debug steamcache issues with Wireshark. You can also set steamcache to use your network's default DNS server instead of the default Google DNS.

**Comment by kixelated** [comment]
Also I'll try to reproduce later tonight.

**Comment by TestCandidate** [comment]
I'd be grateful if you could try and reproduce soon. 
your result will help me make a decision on how to proceed with this.

I tried increasing the resources of my VM. that wasn't any help.

I haven't tried with battlenet and the others. 

On another note, my network use Google's DNS anyway.  so it's the same. 

Please let me know if you could think of any suggestion that could help. so i could try.

thanks :)

**Comment by TestCandidate** [comment]
Hi @kixelated . were you able to reproduce the problem?

**Comment by kixelated** [comment]
Hey TestCandidate, I've been really busy this week at work. I'll take a look over the weekend. Let me know if you get something working in the meantime because that will help diagnose the issue.

**Comment by TestCandidate** [comment]
well what i did is a clean installation on a fresh VM  to double check everything.  the problem persisted.

I'm not sure if ubuntu version has something to do with that. i highly doubt it. but im gonna try it on the ubuntu 14.

**Comment by kixelated** [comment]
I doubt it. We're using docker so you won't see much difference unless you're using some old kernel. Even then, there's no reason why Origin would be slow and not the others. 

I don't know why I didn't ask earlier, but can you post the logs when you try to download from Origin?

**Comment by TestCandidate** [comment]
I can try. but It'll take a while as I'll need to re-setup. 

Where is the log file you want me to post located? I"ll work on it right now.

Thanks

**Comment by kixelated** [comment]
The readme should have the info on how to get logs. The logs will be printed inline if you're just using docker-compose without the -d option. If you're using -d, you'll have to run `docker-compose logs http`.

I'm mostly looking for the steamcache-http logs. There should be a line for every http request. If you don't see any logs, then look at the DNS logs.

**Comment by TestCandidate** [comment]
Yeah. I've seen these logs before. 
they were always forwarded to origin servers as i didn't get to cache anything because of the speed.

Setting up a new VM now. I"ll post some logs soon.

**Comment by TestCandidate** [comment]
Here is the screenshot. 
![image](https://cloud.githubusercontent.com/assets/22873773/26745606/f3c25fac-47f3-11e7-95ea-f619faedc083.png)

I have highlighted some stuff that might be causing the problem? 
I'm not sure to be honest. 
Any ideas? 
Let me know if you need more logs or any further step that helps the debugging process

**Comment by TestCandidate** [comment]
![image](https://cloud.githubusercontent.com/assets/22873773/26745860/42729666-47f5-11e7-9abf-46953c127962.png)
More log. ALOT are missing. this is most problem what's causing the delay. 

But what could be causing the MISS ?

**Comment by TestCandidate** [comment]
** UPDATE ** 
I think Blizzard is having the same problem:
![image](https://cloud.githubusercontent.com/assets/22873773/26745990/f32598a0-47f5-11e7-90a5-f536b43f9064.png)

There are some MISS too for steam. but much less frequent.

**Comment by TestCandidate** [comment]
** UPDATE 2 **
1- I now have better understanding of the cache (miss) terminology. 
so i just realized i didn't make any sense. but well, hopefully you can find something in the log.

2- I left peggie, a 35 MB game on origin to download overnight.
i just uninstalled it, re initiated the setup -> its not cached.

**Comment by TestCandidate** [comment]
Sorry for spamming this thread.
but I've been playing around. 
Finally, I can confirm that the slice size was definitely the problem. i changed it to 1m and it got better, then changed it to 200k and i got full speed.

I am now able to download the game normally. However, it is still not caching:
1- I installed the game.
2- Uninstalled.
3- Re-Installed -> downloading again (not cached)
